### ISSUE TITLE
Suggestion for running with "end-to-end" minizinc program

### ISSUE THREAD

**Issue by hakank** [PatrickTrentin88/fzn2omt#1]
Nowadays I'm almost always running the "end-to-end" minizinc program with the following syntax:

   $ minizinc -s -a model.mzn --solver optimathsat
or
   $ minizinc -n 2 model.mzn --solver optimathsat

But for fzn2optimathmath.py to work with this work flow, it needs to accept these two parameters:
 -a: i.e.  --all-solutions
 -n <N> : i.e. --max-solutions

It would be great if you can add these two shortcuts (-a and -n) to the program:

    parser.add_argument("--all-solutions", "-a", help="Print all solutions of the input problem. If this is an optimization problem, it prints all solutions with the same optimal value.", action="store_true", default=False)

    parser.add_argument("--max-solutions","-n", help="Maximum number of solutions printed.", metavar="N", type=int, default=0)

**Comment by PatrickTrentin88** [comment]
This is a tentative fix. I introduced some change in the direction you have requested, but it might not be up to your standards. Let me know what you think.

New options: 

```
  --max-solutions N, -n N
                        Maximum number of solutions printed.
  --all-solutions, -a   Print all solutions of the input problem. With
                        satisfaction problems, it enables '--all-solutions-
                        opt'. With optimization problems, it enables '--
                        partial-solutions'.
```

Notice that `--all-solutions` now behaves as `--all-solutions` from most MiniZinc solvers, and the old `--all-solutions` has been renamed to `--all-solutions-opt`. 

**Question:** do you expect `--max-solutions` to limit the number of partial solutions printed with an optimization problem? If the maximum number of partial solutions is hit, should the solver still search for an optimal solution or terminate immediately? 

At the moment, I think that `OptiMathSAT` does not count any partial solution towards the value of `--max-solutions`.

**Comment by hakank** [comment]
Thanks for the fix, Patrick.

According to https://www.minizinc.org/doc-2.4.3/en/fzn-spec.html#command-line-interface-and-standard-options for the -n N parameter: "Instructs the solver to stop after reporting i solutions (only used with satisfaction problems)." So, it's not really defined what should be happen when stating the  -n N parameter for optimization problem.

For optimization problem I personally prefer if only the first N solutions are printed, if possible. Gecode has this behaviour but other solvers (e.g. Chuffed) only print the optimal solution.

The specification for the -a flag is: "Instructs the solver to report all solutions in the case of satisfaction problems, or print intermediate solutions of increasing quality in the case of optimisation problems."

fzn2optmath.py shows the intermediate solutions, but it seems that it wait to print them until it finds the optimal solution. Would it be possible that the intermediate solutions are printed directly they are found?

**Comment by PatrickTrentin88** [comment]
> Thanks for the fix, Patrick.
> 
> According to https://www.minizinc.org/doc-2.4.3/en/fzn-spec.html#command-line-interface-and-standard-options for the -n N parameter: "Instructs the solver to stop after reporting i solutions (only used with satisfaction problems)." So, it's not really defined what should be happen when stating the -n N parameter for optimization problem.

In `OptiMathSAT`, the `-n N` parameter affects the number of solutions printed by `--all-solutions-opt` as follows: in satisfaction mode, up to `N` satisfiable models are printed; in optimization mode, up to `N` equi-optimal models are printed.

The `-n N` limits the number of solutions printed by `-a / --all-solutions` ~~only in satisfaction mode, whereas in optimization mode it has no effect~~ exactly as described above.

> 
> For optimization problem I personally prefer if only the first N solutions are printed, if possible. Gecode has this behaviour but other solvers (e.g. Chuffed) only print the optimal solution.

~~It is a bit counter-intuitive for me to have an option that stops the optimization search after enumerating `N` sub-optimal solutions. However, this is not necessarily a difficult change to make in the source code so I'm adding it to the TODO-list of `OptiMathSAT` for the next release.~~

> 
> The specification for the -a flag is: "Instructs the solver to report all solutions in the case of satisfaction problems, or print intermediate solutions of increasing quality in the case of optimisation problems."
> 
> fzn2optmath.py shows the intermediate solutions, but it seems that it wait to print them until it finds the optimal solution. Would it be possible that the intermediate solutions are printed directly they are found?

Good point! This is actually an artifact of the `subprocess.run()` call inside the source code, whereas `OptiMathSAT` prints solutions as he finds them. I'll have that fixed ASAP.

**Comment by hakank** [comment]
The -n N for satisfaction problem is correctly showing N solutions. 

Using both -a and -n N shows first the intermediate solutions and the N optimal solutions. This is a great feature!

Great that you will fix how intermediate solutions are printed (as well as N optimal solutions I hope).

**Comment by PatrickTrentin88** [comment]
> The -n N for satisfaction problem is correctly showing N solutions.
> 
> Using both -a and -n N shows first the intermediate solutions and the N optimal solutions. This is a great feature!

Thanks for remarking this.

> 
> Great that you will fix how intermediate solutions are printed (as well as N optimal solutions I hope).

I have tested it with one of the hardest benchmarks I have and it appears to work as intended.

Would you like anything else to be improved? :)

**Comment by hakank** [comment]
Thanks for your fixes. It seems to work wonderful.

One problem I have is with the .msc file (https://www.minizinc.org/doc-2.4.3/en/fzn-spec.html#sec-cmdline-conffiles and see below for my settings): I must have a wrapper (which happens to be a Perl program) to run optimathsat as a solver. It just runs the Python program using fzn2optimathsat.py with the proper parameters, e.g.
    
       # This is the Perl wrapper (slightly simplified version) 
       my $args = join "", @ARGS;
       system "/home/hakank/g12/fzn2omt/fzn2omt/fzn2optimathsat.py -input=fzn $args";

When setting this Perl wrapper as executable

       ...
      "executable": /home/hakank/g12/optimathsat/optimathsat_solver.pl",
       ...

it works. 

However, when setting the Python program as executable:

     "executable": "/home/hakank/g12/fzn2omt/fzn2omt/fzn2optimathsat.py -input=fzn",

the following error is thrown from the minizinc program:

       MiniZinc: internal error: Error occurred when executing FZN solver with command "/home/hakank/g12/fzn2omt/fzn2omt/fzn2optimathsat.py -input=fzn -a /tmp/mznfileUONoss.fzn ".

(Note that the proper parameter -a is propagated correctly to the Python program.)

The Python program is in the $PATH and is executable so that should not be the problem.

Running the program from the command line works without any problem, e.g.

     $ mzn2fzn zebra.mzn
     $ /home/hakank/g12/fzn2omt/fzn2omt/fzn2optimathsat.py -input=fzn -a zebra.fzn

Can you see any problem with my setup? The complete .msc file is here:

    {
      "id": "optimathsat",
      "name": "optimathsat",
      "description": "OptiMathSAT",
      "version": "1.6.4",
      "mznlib": "",
      "executable": "/home/hakank/g12/fzn2omt/fzn2omt/fzn2optimathsat.py -input=fzn",
      "tags": ["cp","int"],
      "stdFlags": ["-a","-n","-p","-r","-f"],
      "supportsMzn": false,
      "supportsFzn": true,
      "needsSolns2Out": true,
      "needsMznExecutable": false,
      "needsStdlibDir": false,
      "isGUIApplication": false
     }

This file, named as "optimatsat.msc", should be placed in the directory "share/minizinc/solvers" in the minizinc structure. Then one can use the solver as 
    
     $ minizinc zebra.mzn --solver optimatsat -a -s

I'll test some more and come back to you. :-)

**Comment by PatrickTrentin88** [comment]
@hakank It may be the option `-input=fzn`, it is not required by `fzn2optimathsat.py`. If that doesn't work, please ping me that I take a second look ;)

Is it possible that options `-p -r -f` are sent to the python script as well? I can make the script capture and ignore them instead of passing them to OptiMathSAT.

**Comment by hakank** [comment]
Regarding `-input=fzn`: Yes, removing it fixed the problem. Excellent! I thought that this parameter was required for the program to work. But  now I realize that a program called fzn2optimathsat.py surely knows that it is FlatZinc format. :-)

The other parameters in stdFkags list in the .msc file can be removed from the file, I just copied the line from the some other .msc file. However, if optimathsat support any of them it would be great: 

      -p <number of threads/processes>: for parallel computing
      -r <n> : random  seed n
      -f: use a "free" search heuristic instead of the one stated in the model

Come to think about it, it might be better if you ignore then so that they are not used accidentally and throw strange errors.
  

I also notice that the final line "=========="  for a complete solution is not printed when running it via minizinc program (it's not shown when running via my Perl wrapper either). It's printed when running fzn2optimathsat.py from the command line.

      $ minizinc zebra.mzn --solver optimathsat -a        
      % allsat model
      zebra:
      nation = [3, 4, 2, 1, 5]
      colour = [3, 5, 4, 1, 2]
      animal = [4, 1, 2, 5, 3]
      drink  = [5, 2, 3, 4, 1]
      smoke  = [3, 1, 2, 4, 5]
      ----------

And 

     $ mzn2fzn zebra.mzn
     $  /home/hakank/g12/fzn2omt/fzn2omt/fzn2optimathsat.py zebra.fzn -a
     % allsat model
     nation = array1d(0..4, [3, 4, 2, 1, 5]);
     colour = array1d(0..4, [3, 5, 4, 1, 2]);
     animal = array1d(0..4, [4, 1, 2, 5, 3]);
     drink = array1d(0..4, [5, 2, 3, 4, 1]);
     smoke = array1d(0..4, [3, 1, 2, 4, 5]);
     ----------
     =========

Perhaps it's the minizinc programs that are confused here.

**Comment by PatrickTrentin88** [comment]
> Regarding `-input=fzn`: Yes, removing it fixed the problem. Excellent! I thought that this parameter was required for the program to work. But now I realize that a program called fzn2optimathsat.py surely knows that it is FlatZinc format. :-)

Glad it helped

> The other parameters in stdFkags list in the .msc file can be removed from the file, I just copied the line from the some other .msc file. However, if optimathsat support any of them it would be great:
> 
> ```
>   -p <number of threads/processes>: for parallel computing
>   -r <n> : random  seed n
>   -f: use a "free" search heuristic instead of the one stated in the model
> ```

I can hook up `-r` with the random seed option inherited from MathSAT5. The search with OptiMathSAT is always free and the solver is always mono-core so I can set them up for being ignored.

> 
> I also notice that the final line "==========" for a complete solution is not printed when running it via minizinc program (it's not shown when running via my Perl wrapper either). It's printed when running fzn2optimathsat.py from the command line.
> 
> ```
>   $ minizinc zebra.mzn --solver optimathsat -a        
>   % allsat model
>   zebra:
>   nation = [3, 4, 2, 1, 5]
>   colour = [3, 5, 4, 1, 2]
>   animal = [4, 1, 2, 5, 3]
>   drink  = [5, 2, 3, 4, 1]
>   smoke  = [3, 1, 2, 4, 5]
>   ----------
> ```
> 
> And
> 
> ```
>  $ mzn2fzn zebra.mzn
>  $  /home/hakank/g12/fzn2omt/fzn2omt/fzn2optimathsat.py zebra.fzn -a
>  % allsat model
>  nation = array1d(0..4, [3, 4, 2, 1, 5]);
>  colour = array1d(0..4, [3, 5, 4, 1, 2]);
>  animal = array1d(0..4, [4, 1, 2, 5, 3]);
>  drink = array1d(0..4, [5, 2, 3, 4, 1]);
>  smoke = array1d(0..4, [3, 1, 2, 4, 5]);
>  ----------
>  =========
> ```
> 
> Perhaps it's the minizinc programs that are confused here.

I'll take a look at the output streams used by OptiMathSAT just to be sure.

**Comment by PatrickTrentin88** [comment]
> I also notice that the final line "==========" for a complete solution is not printed when running it via minizinc program (it's not shown when running via my Perl wrapper either). It's printed when running fzn2optimathsat.py from the command line.

It appears that OptiMathSAT is printing one less `=` symbol than it should. It will be fixed in the next release. Is it urgent? I can generate a linux/windows binary and send it to you privately.

**Comment by hakank** [comment]
It's not urgent. Please do it in your own time schedule.

**Comment by hakank** [comment]
@PatrickTrentin88 I close this since all the reported stuff has been fixed or handled in other ways.
