### ISSUE TITLE
[Enhancement] Running on Python 3.6

### ISSUE THREAD

**Issue by GustavBjordal** [PatrickTrentin88/fzn2omt#11]
I wanted to run fzn2optimathsat.py on some hardware that only had python 3.6 installed.

By changing line 62 of fzn2optimathsat.py from `subprocess.run(args, text=True, check=True)` into `subprocess.run(args, universal_newlines=True, check=True)` I can run fzn2optimathsat.py under Python 3.6. 
It seems that `text` is just an alias for `universal_newlines ` that was [introduced in 3.7](https://docs.python.org/3.7/library/subprocess.html)  anyway.

Are there any other 3.7 features that are actually used by the script? Otherwise this seems like an easy enhancement for lowering the version requirements.

**Comment by PatrickTrentin88** [comment]
Change made, Thanks!
