### ISSUE TITLE
Python required version is too low

### ISSUE THREAD

**Issue by JoanEspasa** [PatrickTrentin88/fzn2omt#2]
Good morning,

Just wanted to note a very small issue. According to the docs and code the minimum required version of python is 3.5, but the `text` parameter for `subprocess.run` was introduced in 3.7.

Before that it was called `universal_newlines` instead of `text` and its semantics are the same.

Cheers! :)

**Comment by PatrickTrentin88** [comment]
@JoanEspasa Great feedback, thank you!
