### ISSUE TITLE
Add FlatZinc compiler to SMT-LIBv2 without OMT extensions for CVC4

### ISSUE THREAD

**Issue by kw90** [PatrickTrentin88/fzn2omt#3]
Hi,

I have used this library successfully to convert a `FlatZinc` model to `Z3`, thank you very much for this work!
Now, I would also like to generate `SMT-LIBv2` compliant models for [`CVC4`](https://cvc4.github.io/). Is there any way to do this using your scripts? As far as I understand, `CVC4` requires 'pure' `SMT-LIBv2` input.

Cheers

**Comment by PatrickTrentin88** [comment]
@kw90 I can extend the project to support `CVC4`.

- How urgent is this?
- Last time I checked, `CVC4` did not support optimization goals. Do you need any hook for handling that?

**Comment by kw90** [comment]
Thanks for the fast feedback.

> How urgent is this?

We would need it in about 3-4 weeks time. Can I help you in any way (although my background in optimization is rather limited)?

> Last time I checked, CVC4 did not support optimization goals.

True, that seems still to be the case.

> Do you need any hook for handling that?

What kind of hook would be possible here?

**Comment by PatrickTrentin88** [comment]
> We would need it in about 3-4 weeks time. 

My current estimate is that it should take a few hours at most. I might be able to work on it in a few days.

> Can I help you in any way (although my background in optimization is rather limited)?

Did you try translating a satisfaction FlatZinc problem into SMT-LIB for Z3 and run CVC4 over it?
What error did you get?

> What kind of hook would be possible here?

One can address the lack of support for optimization problems in several ways:

- throw an exception and refuse to translate optimization problems
- print a warning, translate the SMT part of the FlatZinc file and ignore the optimization goal
- print a warning, translate the SMT part of the FlatZinc file and add information about the
  expected objective function as a comment

If you plan to write your own optimizer on top of `CVC-4`, then last choice is the most user friendly. If you are not going to handle optimization problems but also don't want to spend time writing your own filter to discard them, then the first choice is the most user friendly. It all comes down to your use case, which I don't know about.

**Comment by kw90** [comment]
> Did you try translating a satisfaction FlatZinc problem into SMT-LIB for Z3 and run CVC4 over it?
> What error did you get?

Got it to work on the online [app](https://cvc4.github.io/app/) on one of our instances. I used the `fzn2smt2.py` script and setting the solver argument to `optimathsat` to generate the file. Initially this gave the following error:

```
(error "Parse Error: /code.txt:14.14: cannot declare or define symbol `.8'; 
    symbols starting with . and @ are reserved in SMT-LIB
```

Apparently function names starting with a dot are reserved, but `Z3` somehow does not complain about this. So all I had to do to fix the satisfaction problem in the `smt2` file was to find and rename all the functions starting with a dot using the following regexes in Vim:

:%s/define-fun \./define-fun f/g
:%s/\.\(\d\)/f\1/g

Probably we should also add `(set-logic ALL)` to remove warnings or allowing to set a stricter logic.

As for the hook for handling the lack of support of optimization goals I think the latter
> print a warning, translate the SMT part of the FlatZinc file and add information about the expected objective function as a comment

would serve the purpose the best.

Thanks and happy easter! :)

**Comment by PatrickTrentin88** [comment]
> > Did you try translating a satisfaction FlatZinc problem into SMT-LIB for Z3 and run CVC4 over it?
> > What error did you get?
> 
> Got it to work on the online [app](https://cvc4.github.io/app/) on one of our instances. I used the `fzn2smt2.py` script and setting the solver argument to `optimathsat` to generate the file. Initially this gave the following error:
> 
> ```
> (error "Parse Error: /code.txt:14.14: cannot declare or define symbol `.8'; 
>     symbols starting with . and @ are reserved in SMT-LIB
> ```
> 
> Apparently function names starting with a dot are reserved, but `Z3` somehow does not complain about this. So all I had to do to fix the satisfaction problem in the `smt2` file was to find and rename all the functions starting with a dot using the following regexes in Vim:
> 
> :%s/define-fun ./define-fun f/g
> :%s/.(\d)/f\1/g
> 
> Probably we should also add `(set-logic ALL)` to remove warnings or allowing to set a stricter logic.

Great work! I would also check the translation of mixed int/real problems. FlatZinc has strong type rules, but MathSAT does not: it considers every `int` as a special type of `real`. So it can happen that an integer `1` is printed as `1.0`. I know this confuses some other SMT solvers, but I am not sure about CVC-4.

> 
> As for the hook for handling the lack of support of optimization goals I think the latter
> 
> > print a warning, translate the SMT part of the FlatZinc file and add information about the expected objective function as a comment
> 
> would serve the purpose the best.
> 
> Thanks and happy easter! :)

That will do then. Happy Easter to you!
