### ISSUE TITLE
Solution recovery for fzn2z3.py

### ISSUE THREAD

**Issue by JoanEspasa** [PatrickTrentin88/fzn2omt#4]
These days I'm trying to incorporate the fzn2omt scripts in a bigger pipeline to test the encodings thoroughly :)

I'm running some comparisons and I see that the fzn2optimathsat returns the solution in a fzn format, but its not the case with the fzn2z3, as it returns the solution in the Z3 format.

Would it be possible for it to return it also in a fzn format?

Thanks!

**Comment by PatrickTrentin88** [comment]
@JoanEspasa This is because `OptiMathSAT` has a native FlatZinc interface, whereas `Z3`, `Barcelogic` and `CVC4` do not.

This might take some time to get done.

**Comment by JoanEspasa** [comment]
Thanks Patrick!

We use that mainly for correctness validation (i.e. the encoding and solver are sound and complete)

**Comment by PatrickTrentin88** [comment]
@JoanEspasa I have extended the nightly build of `OptiMathSAT` with the option of printing the mapping between the internal SMT-LIB variables and the output variables of the FlatZinc frontend. **e.g.** given a trivial model as follows:

```
var int: x1 ::output_var;
var int: x2 ::output_var = 4;
var int: x3 ::output_var;
var float: y ::output_var;
array [1..3] of var int: a ::output_array([1..3]) = [x1, x2, x3];
var set of 1..3: k1 ::output_var;
var set of 1..9: k2 ::output_var = {4, 5, 6};
var set of 1..3: k3 ::output_var;

constraint int_eq(x3, 6);
constraint float_eq(y, 7.8);
constraint set_eq(k3, {1, 2});

solve satisfy;
```

it prints:

```
~$ ./optimathsat -input=fzn \
                           -debug.api_call_trace=1 \
                           -debug.api_call_trace_dump_config=False \
                           -debug.solver_enabled=False \
                           -debug.api_call_trace_filename=output.smt2 \
                           input.fzn 
; x1 = x1;
; x2 = 4;
; x3 = x3;
; y = y;
; k1 = {.pvt_fzn.k1.1, .pvt_fzn.k1.2, .pvt_fzn.k1.3};
; k2 = {4, 5, 6};
; k3 = {.pvt_fzn.k3.1, .pvt_fzn.k3.2, .pvt_fzn.k3.3};
; a = array1d(1..3, [x1, 4, x3]);
```

This should simplify reversing the model of `z3` and `bclt` to print it in FlatZinc format. I still don't have time to work on it yet.

**Comment by PatrickTrentin88** [comment]
@JoanEspasa This issue is now fixed.

This project now requires **OptiMathSAT 1.7.0** or better in order to work.
The release will follow in a few days.
